In [83]:
#负定矩阵
import numpy as np
A =np.array([[-2,-3,-1],
            [-3,-6,-4],
            [-1,-4,-5]])

v = np.array([3,5,6])

print('给定向量任意向量v:',v)
print('求解矩阵A正定判定条件结果是：',v.T.dot(A).dot(v))

给定向量任意向量v: [3 5 6]
求解矩阵A正定判定条件结果是： -714


In [84]:
#负定矩阵
import numpy as np
B =np.array([[5,-1,-4],
            [1,3,-2],
            [-4,-2,7]])

v = np.array([3,5,6])

print('给定向量任意向量v:',v)
print('求解矩阵A正定判定条件结果是：',v.T.dot(A).dot(v))

给定向量任意向量v: [3 5 6]
求解矩阵A正定判定条件结果是： 108


In [89]:
###根据特征值进行判定 全部是正数为正定矩阵
w,v = np.linalg.eig(A)
print('矩阵A的特征值特征向量是:')
display(w,v)

矩阵A的特征值特征向量是:


array([10.41138182,  3.31298965,  1.27562853])

array([[-0.53465096, -0.69033123,  0.73598789],
       [-0.28666499,  0.57768602,  0.28527531],
       [ 0.79496637, -0.43557049,  0.61395425]])

In [88]:
###根据特征值进行判定 不是负定矩阵，也不是正定矩阵  是不定矩阵
w,v = np.linalg.eig(B)
print('矩阵A的特征值特征向量是:')
display(w,v)

矩阵A的特征值特征向量是:


array([16.10241769,  0.19192041, -1.2943381 ])

array([[ 0.23165721,  0.95684242, -0.17546374],
       [ 0.59582744, -0.28213926, -0.75192227],
       [ 0.76897633, -0.0696421 ,  0.63547256]])