In [2]:
#线性回归房价预测
import numpy as np 
from sklearn import datasets
from sklearn.linear_model import LinearRegression
import pandas as pd

In [4]:
 # 读取Excel文件
data_file = "房屋数据集_800条.xlsx"
df = pd.read_excel(data_file)
df.shape

(800, 12)

In [6]:
#准备特征数据
feature_names = [
            '建筑面积(平方米)', '卧室数量', '卫生间数量', '楼层数', '建造年份',
            '地理位置评分', '距市中心距离(公里)', '是否有车库', '装修等级', '周边学校数量'
        ]



In [18]:
X = df[feature_names].copy()
# 将分类变量转换为数值变量
X['是否有车库'] = X['是否有车库'].map({'是': 1, '否': 0})
X['装修等级'] = X['装修等级'].map({'简装': 0, '中装': 1, '精装': 2, '豪装': 3})
display(x.shape)
#准备目标数据
target_name = '房价(万元)'
y = df[target_name].copy()
display(y.shape)

(800, 10)

(800,)

In [19]:
X[:20]

建筑面积(平方米)  卧室数量  卫生间数量  楼层数  建造年份  地理位置评分  距市中心距离(公里)  是否有车库  装修等级  周边学校数量
0       139.9     2      1    2  1964      10         8.0      1     1       2
1       114.5     3      2    3  2015       1         5.2      1     2       1
2       145.9     2      3    2  1991       9         4.4      1     0       5
3       180.9     1      1    3  1979       6         1.8      1     0       1
4       110.6     3      1    1  2009       9        16.2      0     1       3
5       110.6     4      1    1  1970       7         7.3      0     0       1
6       183.2     4      3    2  1974       1        29.7      1     1       5
7       150.7     5      3    2  1991       1        17.7      0     0       4
8       101.2     2      2    2  1987       6         5.0      1     2       4
9       141.7     3      3    3  1981       5        21.0      1     0       3
10      101.5     5      2    2  2000       9        27.0      1     2       2
11      101.4     3      2    1  1976       2        22.6      1     0       3
12      129.7     2      3    3  2018       8         3.2      0     3       4
13       43.5     4      2    2  1985       5        27.0      0     2       0
14       51.0     1      3    3  2003       2        24.0      0     0       0
15       97.5     4      2    3  1966      10         5.6      1     2       1
16       79.5     5      3    2  2001       6         2.5      0     1       5
17      132.6     1      3    3  2016      10        17.2      1     2       1
18       83.7     5      2    1  1985       8         5.5      0     1       0
19       63.5     2      1    1  1984       4        25.2      1     1       4

In [31]:
#数据拆分 80%训练数据集 20%测试集
#打乱数据
index = np.arange(800)
np.random.shuffle(index)

train_index = index[:640]
test_index = index[640:]
#train_index

In [52]:
#80%训练数据集
x_train = X.values[train_index]
y_train = y.values[train_index]
display(x_train.shape,y_train.shape)

(640, 10)

(640,)

In [53]:
#20%测试数据集
x_test = X.values[test_index]
y_test = y.values[test_index]
display(x_test.shape,y_test.shape)


(160, 10)

(160,)

In [54]:
#数据建模
np.set_printoptions(suppress=True) #关闭科学计数法

model = LinearRegression(fit_intercept=True) 
model.fit(x_train,y_train)
#正数表示正相关 反之则是负相关
display(model.coef_,model.intercept_)

array([ 0.76165866, 21.25971249, 15.21789319,  3.69216491,  0.5453437 ,
        9.83551533, -2.02626007, 12.63461393, 22.68359575,  6.9748869 ])

np.float64(-1096.063018673563)

In [55]:
#数据特征
X.columns

Index(['建筑面积(平方米)', '卧室数量', '卫生间数量', '楼层数', '建造年份', '地理位置评分', '距市中心距离(公里)',
       '是否有车库', '装修等级', '周边学校数量'],
      dtype='object')

In [56]:
#模型验证、应用
y_ = model.predict(x_test).round(2)
y_[:30]

array([212.72, 328.78, 312.93, 247.67, 371.43, 180.51, 260.01, 260.29,
       204.13, 306.75, 337.5 , 209.98, 319.71, 302.65, 342.2 , 213.31,
       278.08, 349.14, 308.83, 277.38, 341.8 , 237.85, 333.35, 330.34,
       200.56, 246.27, 284.81, 216.25, 229.63, 250.67])

In [58]:
y_test[:30]

array([206.89, 334.43, 380.08, 226.84, 299.94, 175.75, 244.21, 248.64,
       193.01, 259.31, 355.65, 218.87, 360.66, 291.41, 300.98, 234.  ,
       236.96, 342.62, 342.02, 286.57, 337.32, 243.07, 299.29, 322.64,
       202.72, 223.25, 308.84, 210.93, 227.7 , 216.15])

In [59]:
#模型评估 最大值是1  可以小于0 
#越接近于1说明算法越优秀
model.score(x_test,y_test)

0.8299393107086008

$R^2 = 1 - \frac{u}{v}$

In [ ]:
#手动计算

In [61]:
y_pred = y_
y_true = y_test
u = ((y_true - y_pred) ** 2).sum()
u

np.float64(116889.74759999999)

In [62]:
v = ((y_true - y_true.mean())**2).sum()
v

np.float64(687348.508094375)

In [64]:
r = 1 - u / v
r

np.float64(0.8299410761448097)

In [73]:
#训练数据评分

model.score(x_train,y_train)

0.8176628025369181

In [75]:
#最小二乘法
from sklearn.metrics import mean_squared_error

mean_squared_error(y_true,y_pred)

730.5609225

In [74]:
mean_squared_error(y_train,model.predict(x_train))

811.5449292822647